// Next imports
import { Inter } from 'next/font/google'
import { cookies } from "next/headers";

// Local imports
import './globals.css'
import UpperNav from '@/components/layout/UpperNav';
import Footer from '@/components/layout/Footer';
import ChangePasswordModal from '@/components/ui/ChangePasswordModal';
import { getUserFromToken } from '@/helpers/authentication';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const userToken = cookieStore.get('eport-token') ? cookieStore.get('eport-token').value : null;
  const isLoggedIn = userToken ? true : false;
  const user = getUserFromToken(userToken);

  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossOrigin="anonymous" referrerPolicy="no-referrer" />
      </head>
      <body className={`${inter.className} pt-16 pb-[340px] bg-slate-100 w-screen min-h-screen relative`}>
        <UpperNav isLoggedIn={isLoggedIn} email={user ? user.email : null}/>
        {isLoggedIn ? <ChangePasswordModal /> : null}
        {children}
        <Footer isLoggedIn={isLoggedIn}/>
      </body>
    </html>
  )
}
